// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3H4UkRq3kXvsEeb5tjqoGm48sW2TmUqY',
    appId: '1:227158964783:web:3490ce40cf5d5b3b2da4da',
    messagingSenderId: '227158964783',
    projectId: 'ngoproject-d9435',
    authDomain: 'ngoproject-d9435.firebaseapp.com',
    storageBucket: 'ngoproject-d9435.appspot.com',
    measurementId: 'G-VQ735DQ8LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavbPoBjzLWTY7_JU2JpXaIrgPdByiiig',
    appId: '1:227158964783:android:8b341a168ff054682da4da',
    messagingSenderId: '227158964783',
    projectId: 'ngoproject-d9435',
    storageBucket: 'ngoproject-d9435.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_MYtcaLP-LRAzW-MG2WuALU1eq60DVaY',
    appId: '1:227158964783:ios:151f7bfe678bf6652da4da',
    messagingSenderId: '227158964783',
    projectId: 'ngoproject-d9435',
    storageBucket: 'ngoproject-d9435.appspot.com',
    iosBundleId: 'com.example.ngoAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_MYtcaLP-LRAzW-MG2WuALU1eq60DVaY',
    appId: '1:227158964783:ios:151f7bfe678bf6652da4da',
    messagingSenderId: '227158964783',
    projectId: 'ngoproject-d9435',
    storageBucket: 'ngoproject-d9435.appspot.com',
    iosBundleId: 'com.example.ngoAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3H4UkRq3kXvsEeb5tjqoGm48sW2TmUqY',
    appId: '1:227158964783:web:761db2c5d971c0462da4da',
    messagingSenderId: '227158964783',
    projectId: 'ngoproject-d9435',
    authDomain: 'ngoproject-d9435.firebaseapp.com',
    storageBucket: 'ngoproject-d9435.appspot.com',
    measurementId: 'G-FZFBNVTFBR',
  );
}
